### ISSUE TITLE
About asqatasun runner

### ISSUE THREAD

**Issue by softwareklinic** [Asqatasun/Asqatasun#70]
Is runner included in the tarball... or do i need to install it separately...

**Comment by jkowalczyk** [comment]
Hi, 

The runner used to be packaged with the webapp.

We decided to split this, but we forgot to upload the runner as an attached binary of the release.
(we need to add this in our release process).

Anyway, I've just added it and you can now download it from the release page.

So, to answer your question, you need to install it separately. The archive contains an execution context that just needs to be set with the mysql database info (url, user, password) in the `conf/context/asqatasun.conf` file.

Once set, you just need to call the asqatasun.sh script with the `bin` folder.

Here is a copy of the usage of the script : 

```
Please specify at least one URL

usage: ./bin/asqatasun.sh [OPTIONS]... [URL OR FILE OR SCENARIO]...
                          
 -d,--display <arg>       Value of the display
 -f,--firefox-bin <arg>   Path to the firefox bin.
 -h,--help                Show this message.
 -l,--level <arg>         Level :
                          - "Or" for Gold level or AAA level,
                          - "Ar" for Silver level or AA level (default),
                          - "Bz" for Bronze level or A level
 -o,--output <arg>        Path to the output result file.
 -r,--referential <arg>   Referential :
                          - "Aw22" for Accessiweb 2.2 (default)
                          - "Rgaa22" for Rgaa 2.2
                          - "Rgaa30" for Rgaa 3.0
 -t,--audit-type <arg>    Audit type :
                          - "Page" for page audit (default)
                          - "File" for file audit
                          - "Scenario" for scenario audit
                          - "Site" for site audit
 -x,--xmx-value <arg>     Xmx value set to the process (without 'M' at the
                          end):
                          - default is 256
                          - must be superior to 64 (Xms value)
```

If you run it from a headless context (server), you need to start the xvfb service and use the dedicated script option to set it.

If you run it from a desktop, you don't need this, and you'll get the surprise to see the browser coming up and then disappearing. 

Don't hesitate if you have more questions.

Thanks again for this valuable feedback !!

Koj

**Comment by softwareklinic** [comment]
Ty



Regards,
Keyur

On Feb 10, 2016, at 11:51 AM, Jérôme Kowalczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

The runner used to be packaged with the webapp.

We decided to split this, but we forgot to upload the runner as an attached binary of the release.
(we need to add this in our release process).

Anyway, I've just added it and you can now download it from the release page.

So, to answer your question, you need to install it separately. The archive contains an execution context that just needs to be set with the mysql database info (url, user, password) in the conf/context/asqatasun.conf file.

Once set, you just need to call the asqatasun.sh script with the bin folder.

Here is a copy of the usage of the script :

Please specify at least one URL

usage: ./bin/asqatasun.sh [OPTIONS]... [URL OR FILE OR SCENARIO]...

 -d,--display <arg>       Value of the display
 -f,--firefox-bin <arg>   Path to the firefox bin.
 -h,--help                Show this message.
 -l,--level <arg>         Level :
                          - "Or" for Gold level or AAA level,
                          - "Ar" for Silver level or AA level (default),
                          - "Bz" for Bronze level or A level
 -o,--output <arg>        Path to the output result file.
 -r,--referential <arg>   Referential :
                          - "Aw22" for Accessiweb 2.2 (default)
                          - "Rgaa22" for Rgaa 2.2
                          - "Rgaa30" for Rgaa 3.0
 -t,--audit-type <arg>    Audit type :
                          - "Page" for page audit (default)
                          - "File" for file audit
                          - "Scenario" for scenario audit
                          - "Site" for site audit
 -x,--xmx-value <arg>     Xmx value set to the process (without 'M' at the
                          end):
                          - default is 256
                          - must be superior to 64 (Xms value)


If you run it from a headless context (server), you need to start the xvfb service and use the dedicated script option to set it.

If you run it from a desktop, you don't need this, and you'll get the surprise to see the browser coming up and then disappearing.

Don't hesitate if you have more questions.

Thanks again for this valuable feedback !!

Koj

**Comment by softwareklinic** [comment]
So, both the runner and webapp can point to the same myql DB?

**Comment by jkowalczyk** [comment]
Yes,

That's the idea (waiting for a pretty Rest API allowing us to skip the use of the runner, just like sonarqube for instance)

The runner will write the results in the db, and the web-app is used in this case as a audit result reader.

Koj

**Comment by softwareklinic** [comment]
looks like some reference to tanaguru

Exception in thread "main" org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:conf/context/beans-tanaguru.xml]


when i try to run the runner - gives above error...

**Comment by softwareklinic** [comment]
<import resource="classpath:conf/context/beans-analyser.xml"/><import resource="classpath:conf/context/beans-audit.xml"/><import resource="classpath:conf/context/beans-consolidator.xml"/><import resource="classpath:conf/context/beans-contentadapter.xml"/><import resource="classpath:conf/context/beans-contentloader.xml"/><import resource="classpath:conf/context/beans-crawler.xml"/><import resource="classpath:conf/context/beans-factories.xml"/><import resource="classpath:conf/context/beans-logging.xml"/><import resource="classpath:conf/context/beans-nomenclatureloader.xml"/><import resource="classpath:conf/context/beans-parameters.xml"/><import resource="classpath:conf/context/beans-persistence.xml"/><import resource="classpath:conf/context/beans-processor.xml"/><import resource="classpath:conf/context/beans-reference.xml"/><import resource="classpath:conf/context/beans-ruleimplementationloader.xml"/><import resource="classpath:conf/context/beans-scenarioloader.xml"/><import resource="classpath:conf/context/beans-statistics.xml"/><import resource="classpath:conf/context/beans-tanaguru.xml"/>

quite a few

**Comment by jkowalczyk** [comment]
Can you try to edit the application-context.xml file in the `conf/context` folder and replace the tanaguru occurrences by the asqatasun?

**Comment by softwareklinic** [comment]
some more

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor#0' defined in class path resource [conf/context/beans-persistence.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Cannot parse persistence unit from class path resource [conf/tanaguru-persistence.xml]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:733)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:140)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:84)
	at org.asqatasun.runner.Asqatasun.initServices(Asqatasun.java:362)
	at org.asqatasun.runner.Asqatasun.runAuditOnline(Asqatasun.java:224)
	at org.asqatasun.runner.Asqatasun.main(Asqatasun.java:190)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Cannot parse persistence unit from class path resource [conf/tanaguru-persistence.xml]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:424)
	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:277)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.<init>(PersistenceExceptionTranslationInterceptor.java:79)
	at org.springframework.dao.annotation.PersistenceExceptionTranslationAdvisor.<init>(PersistenceExceptionTranslationAdvisor.java:70)
	at org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor.setBeanFactory(PersistenceExceptionTranslationPostProcessor.java:103)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1475)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Cannot parse persistence unit from class path resource [conf/tanaguru-persistence.xml]
	at org.springframework.orm.jpa.persistenceunit.PersistenceUnitReader.readPersistenceUnitInfos(PersistenceUnitReader.java:141)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.readPersistenceUnitInfos(DefaultPersistenceUnitManager.java:380)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.preparePersistenceUnitInfos(DefaultPersistenceUnitManager.java:341)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.afterPropertiesSet(DefaultPersistenceUnitManager.java:326)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:235)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 27 more
Caused by: java.io.FileNotFoundException: class path resource [conf/tanaguru-persistence.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:157)
	at org.springframework.orm.jpa.persistenceunit.PersistenceUnitReader.readPersistenceUnitInfos(PersistenceUnitReader.java:129)
	... 34 more

**Comment by jkowalczyk** [comment]
Ok, 

I think I got it.

Last thing to change is the tanaguru occurrence in the asqatasun.conf file.

Sorry for this, I immediately correct it on the develop branch, and I promise, it will be more stable on the next release ;-)

Koj

**Comment by softwareklinic** [comment]
No
Worries I will try in few



Regards,
Keyur

On Feb 10, 2016, at 12:37 PM, Jérôme Kowalczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok,

I think I got it.

Last thing to change is the tanaguru occurrence in the asqatasun.conf file.

Sorry for this, I immediately correct it on the develop branch, and I promise, it will be more stable on the next release ;-)

Koj

**Comment by softwareklinic** [comment]
System info: host: 'vzwqait-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-25-generic', java.version: '1.7.0_95'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:110)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:195)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:190)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.asqatasun.sebuilder.interpreter.webdriverfactory.FirefoxDriverFactory.make(FirefoxDriverFactory.java:67)
	at com.sebuilder.interpreter.TestRun.initRemoteWebDriver(TestRun.java:223)
	... 29 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ebapps-team@lists.launchpad.net","e":false,"v":"3.0.2","st":1438751895000,"mt":1397665356000},"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com","e":false,"v":"3.0","st":1438751894000,"mt":1420839872000},"{2e1445b0-2682-11e1-bfc2-0800200c9a66}":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}","e":false,"v":"2014.08.06.beta","st":1438751894000,"mt":1407283796000}},"app-system-local":{"online-accounts@lists.launchpad.net":{"d":"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net","e":false,"v":"0.5","st":1438751895000,"mt":1390969548000}}}
1455133769122	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1455133769123	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tmp/anonymous2178006741591714879webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.39.0","st":1455133767000,"mt":1455133767000}},"app-global":{"langpack-en-GB@firefox.mozilla.org":{"d":"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi","e":false,"v":"44.0","st":1453851127000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"39.0","st":1438751793000,"mt":1435579394000},"langpack-en-ZA@firefox.mozilla.org":{"d":"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi","e":false,"v":"44.0","st":1453851127000}},"app-system-share":{"webapps-team@lists.launchpad.net":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net","e":false,"v":"3.0.2","st":1438751895000,"mt":1397665356000},"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com","e":false,"v":"3.0","st":1438751894000,"mt":1420839872000},"{2e1445b0-2682-11e1-bfc2-0800200c9a66}":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}","e":false,"v":"2014.08.06.beta","st":1438751894000,"mt":1407283796000}},"app-system-local":{"online-accounts@lists.launchpad.net":{"d":"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net","e":false,"v":"0.5","st":1438751895000,"mt":1390969548000}}}
1455133769124	addons.xpi	DEBUG	No changes found
1455133769128	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1455133769129	addons.manager	DEBUG	Provider finished startup: XPIProvider
1455133769129	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1455133769129	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1455133769129	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1455133769130	addons.manager	DEBUG	Starting provider: GMPProvider
1455133769134	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1455133769134	addons.manager	DEBUG	Provider finished startup: GMPProvider
1455133769134	addons.manager	DEBUG	Starting provider: PluginProvider
1455133769134	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1455133769135	addons.manager	DEBUG	Provider finished startup: PluginProvider
1455133769135	addons.manager	DEBUG	Completed startup sequence
1455133769229	addons.xpi-utils	DEBUG	Starting async load of XPI database /tmp/anonymous2178006741591714879webdriver-profile/extensions.json
1455133769232	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1455133769232	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1455133769232	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1455133769389	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1455133769389	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1455133769390	addons.xpi-utils	DEBUG	Successfully read XPI database
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 36 more
crash (id+message): 9 org.asqatasun.scenarioloader.exception.ScenarioLoaderException: java.lang.RuntimeException: Test run failed: unable to create driver.

**Comment by softwareklinic** [comment]
Do i need to STOP xvfb??

**Comment by jkowalczyk** [comment]
No, don't think so !!!

Can you make suree  the user that owns the xvfb display is the same as the one that launches the runner?

**Comment by softwareklinic** [comment]
I'm
Good - ty.  The test that we run from runner can those appear in asqatasun web app dashboard?



Regards,
Keyur

On Feb 10, 2016, at 1:56 PM, Jérôme Kowalczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


No, don't think so !!!

Can you make suree the user that owns the xvfb display is the same as the one that launches the runner?

**Comment by jkowalczyk** [comment]
To do so, the runner has to be launched through the jenkins job. That's the main part of the job, i.e creating a link between the "standalone" alone, and a contract in UI.

**Comment by softwareklinic** [comment]
Ok installing Jenkins, building the
Plugin :) and trying
Out



Regards,
Keyur

On Feb 10, 2016, at 2:04 PM, Jérôme Kowalczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


To do so, the runner has to be launched through the jenkins job. That's the main part of the job, i.e creating a link between the "standalone" alone, and a contract in UI.

**Comment by mfaure** [comment]
Hi @softwareklinic, 

Is everything OK for you with the Asqatasun Jenkins Plugin ? The release from @jkowalczyk is good ? May I close this issue ?

**Comment by softwareklinic** [comment]
I'm away this weekend will test it tomorrow and get back



Regards,
Keyur

On Feb 14, 2016, at 3:07 PM, Matthieu FAURE <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @softwareklinic<https://github.com/softwareklinic>,

Is everything OK for you with the Asqatasun Jenkins Plugin ? The release from @jkowalczyk<https://github.com/jkowalczyk> is good ? May I close this issue ?

**Comment by softwareklinic** [comment]
We are going to work today yo integrate Asqatasun wit Jenkins... also, another question --- are you planning to release Sona and Sonar-eclipse plugin as well?

**Comment by mfaure** [comment]
We try to keep having one topic per issue, and github issues are for bugs. To ask question, I suggest you use the [asqatasun forum](http://forum.asqatasun.org/) :)
